### ISSUE TITLE
Cannot build due to unsatisfied dependency error.

### ISSUE THREAD

**Issue by adnan449** [disruptek/nimph#146]
On Fedora Linux 33:

```
     Error: Cannot satisfy the dependency on nimterop 0.6.11 and nimterop 0.6.13
/home/adnan338/proj/nimph/nimph
```

Full version: 
https://pastebin.com/AN3PvnDg

**Comment by disruptek** [comment]
Yes, Nimble has a bug that allows it to install dependencies that won't actually satisfy the software you're trying to install.  The best solution is to install `nimterop-0.6.11` first and then Nimble won't install `nimterop-0.6.13`.

I know, I know.  This is why Nimph was created, after all...

**Comment by disruptek** [comment]
I'm updating the `bootstrap.sh` and `bootstrap-nonimble.sh` files to install the needed version of `nimterop` so that this problem is solved.  Thanks for the report!

**Comment by adnan449** [comment]
Not sure if it's the same issue. But I removed all `nimterop` from my `~/.nimble/pkgs/` and tried to install using nimble. It fails again:

```
[snip]
 Building nimterop/nimterop/toast using c backend
# Resetting /home/adnan338/.cache/nim/nimterop/nimterop/treesitter
# Resetting /home/adnan338/.cache/nim/nimterop/nimterop/treesitter_c
# Resetting /home/adnan338/.cache/nim/nimterop/nimterop/treesitter_cpp
   Warning: Symlink already exists in /home/adnan338/.nimble/bin/loaf. Replacing.
oserr.nim(94)            raiseOSError
Error: unhandled exception: File exists
Additional info: "(\"../pkgs/nimterop-0.6.13/nimterop/toast\", \"/home/adnan338/.nimble/bin/toast\")" [OSError]
```

**Comment by disruptek** [comment]
Per the README, if you cannot build Nimph with Nimble, you should use one of the `bootstrap.sh` or `bootstrap-nonimble.sh` scripts.

Nimph requires `nimterop-0.6.11` or earlier, as per `nimph.nimble`.  I don't know why Nimble wants to install `nimterop-0.6.13` and at this point in my life, I'm not about to find out.
