### ISSUE TITLE
Error on `doctor`ing certain package

### ISSUE THREAD

**Issue by SolitudeSF** [disruptek/nimph#160]
running `nimph doctor` in https://github.com/einheit-tech/kozu results in `Exception: field 'reference' is not accessible for type 'Release' using 'kind = =='`

**Comment by disruptek** [comment]
I cannot reproduce this.  What does `nimph` say?

**Comment by SolitudeSF** [comment]
this is devel compiler

**Comment by disruptek** [comment]
If you build nimph outside release, you can get some debugging output.  Otherwise, without any steps to reproduce this, no idea which commits of which projects you're using, etc...

PRs welcome. :slightly_smiling_face:

**Comment by SolitudeSF** [comment]
idk, it now errors in another place.

**Comment by disruptek** [comment]
FWIW, Nimph doesn't support the `nimble` in mainline Nim's devel branch.
