### ISSUE TITLE
add tilde/caret/wildcards support to nimble

### ISSUE THREAD

**Issue by disruptek** [disruptek/nimph#26]
We are probably going to have to implement these in Nimble if we want them to be useful in public projects.

cc @genotrance

**Comment by genotrance** [comment]
Do you mean pathSubs?

**Comment by disruptek** [comment]
No, I mean the `requires =` statements in the `.nimble`.  I modeled Nimph's off of those of Cargo.  There are also some tests that might be helpful.

**Comment by disruptek** [comment]
You can now play with these using the `roll` command, if it helps.

I'm thinking that given the state of things in Nimbleland, it might be easiest to just patch Nimble to parse `~` and `^` as `>=`, since that's the only useful operator there anyway.  I imagine that Nimble is parsing `3` as `3.*.*`, as today we discovered that some packages exist with 1-dot (eg. `3.1`) versions, and @Solitude managed to find one with 3-dots (eg. `1.2.3.4`).

A better alternative might be to introduce another statement to the `.nimble`.  I've long wanted a way to blacklist version ranges; see #82, so maybe we add a more advanced `requires` statement that can co-exist with a Nimble-friendly `requires`, but which carries additional syntax capabilities (caret/tilde/wildcard).  While we're in there, we add `deficiencies` for #82 and then we've enhanced capabilities without breaking any existing packages or package managers.  Nimble can upgrade to support caret/tilde/wildcard via requires (or the new statements) whenever it likes.

We would almost certainly have to implement #24 as well, of course.

Thoughts?
