### ISSUE TITLE
Incorrect package name rendering

### ISSUE THREAD

**Issue by dumjyl** [disruptek/nimph#89]
The name is rendered as ext. Should be std-ext or std_ext (depending on if going by the repo name or pkgname.nimble).
```
$ nimph
❌ext (https://github.com/dumjyl/std-ext>=1.1.0) missing
```

**Comment by disruptek** [comment]
Closed in b2c7eea487f021caafcacd973f942d284b722c0d but it remains to be seen if this is the right solution.  It's a little more brittle now...
